### ISSUE TITLE
Phantom not running on AWS

### ISSUE THREAD

**Issue by zeus3rd** [amir20/phantomjs-node#514]
Node Version: 4.3.0
Phantom version: 2.0.10
Amazon Server Version: 64bit Amazon Linux 2016.03

Phantom has recently stopped working on our AWS servers. Recent deployments with no related changes are failing to start the phantomjs engine.

The phantom.create() function causes the following error:
Could not spawn [/tmp/deployment/application/node_modules/phantom/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs] executable. Please make sure phantomjs is installed correctly.
Error: spawn /tmp/deployment/application/node_modules/phantom/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT

This error does not occur on Mac workstations, so might be related to the OS relative version of phantom being installed on AWS servers. Either way, the library doesn't seem to selectively choose which version of phantom is installed and instead always installs the latest version.

Perhaps the latest version of phantom doesn't work on AWS and therefore version support would be needed in this library
or
Perhaps the post download install process is not being triggered correctly for some reason.
or
The recent phantomjs.path changes might not be using a correct relative path any more

Please let me know if further information is required.

**Comment by azattelman** [comment]
+1!

**Comment by amir20** [comment]
I think something changed with `phantomjs-prebuilt` because I am getting all kinds of errors suddenly. :( Might be related to https://github.com/Medium/phantomjs/issues/581.

**Comment by amir20** [comment]
I just created a new instance in AWS and it worked. I don't get these errors. Can you give me a way to reproduce?

**Comment by zeus3rd** [comment]
Our issue has been resolved internally however it's worth noting that the recent path change in this library was the culprit.

Our project builds on a CI server where npm install dependancies and builds a deployment folder which goes to our AWS server. Both servers run Linux, however one runs a CI which builds in a different folder position to what our deployment server runs it in.

So the recent path change looks for phantomjs here:
/tmp/deployment/application/node_modules/phantom/node_modules/phantomjs-prebuilt/lib/phantom/bin

Where on our production server it exists here:
/var/app/current/node_modules/phantom/node_modules/phantomjs-prebuilt/lib/phantom/bin

It would be a good idea to either:
- get a relative path from the npm or node environment at run time
- have path loaded relative to the phantom library
- at least add documentation in the README detailing this issue for Continuous Integration projects

Thanks

**Comment by amir20** [comment]
@zeus3rd I want to fix this issue. Some other people have been complaining as well. But I can't reproduce the problem at all. How did you go about fixing it? 

I don't get how the recent changes could have broken int. The module uses `phantomjs-prebuilt` where it provides `phantom.path`. 

I believe the path is absolute. Can you help me identify a better fix here?

**Comment by amir20** [comment]
There was a bug with `phantomjs-prebuilt@2.1.8`. I see it is fixed in `phantomjs-prebuilt@2.1.9`

**Comment by zeus3rd** [comment]
We use the [angular-fullstack-generator](https://github.com/angular-fullstack/generator-angular-fullstack) through yeoman.io to generate our fullstack sever/website.

We then have phantom installed via a normal installation.

To deploy, we push our code to a CI server running buildkite (but any CI server will do the same). We build using the included "grunt build" command to create a "dist" folder in which a new package.json file is created and modules are installed again local to that dist folder. This dist folder is then uploaded to our AWS server.

Because we use this CI server to create our dist folder, the path to phantomjs-prebuilt is relative to the folder on our CI server. When it is released the absolute path to phantomjs-prebuilt changes on another server.

Until recently this worked fine, the the phantom module was referencing the phantomjs-prebuilt path without a problem, which leads us to believe that previous versions were included relative to the folder node was being run from. As our servers eventually migrated from cached versions of npm libraries to refreshed versions last week our servers began to sporadically fail as each one updated something in the dependancy chain and this relative file structure was turned into a direct file structure.

To fix the issue we added the "phantomPath" parameter and overrode the assumed path with a path directly to where we knew phantomjs-prebuilt to be. Admitedly this fix is simple for people to implement, but the circumstances under which they now are required are common but complicated.

Please let me know if there is further information I can provide.

**Comment by amir20** [comment]
@zeus3rd I don't think I understand something. How is it that `phantomjs-prebuilt` path was cached? You say that after it is released since the path is no longer valid it break. 

I think what you are saying is that you use the official phantom installation. But those paths change in different environments. Isn't that the problem of your env then? I highly suggest reading http://12factor.net/. Note 2 suggests to never assume dependencies are install on the host. They should be installed part of the application. This is why I favor `phantomjs-prebuilt`. 

I may have of course misunderstood everything you said. I really didn't want to expose `phantomPath` because of this reason. It only got added because people wanted an older version of phantomjs.

**Comment by amir20** [comment]
Reading this again.

> Until recently this worked fine, the the phantom module was referencing the phantomjs-prebuilt path without a problem, which leads us to believe that previous versions were included relative to the folder node was being run from. As our servers eventually migrated from cached versions of npm libraries to refreshed versions last week our servers began to sporadically fail as each one updated something in the dependancy chain and this relative file structure was turned into a direct file structure.

I don't get this. So you were saying it was always using `phantomjs-prebuilt` and suddenly it started failing. I want to fix this. What caused this to happen do you think? Was there any errors you can share?

**Comment by amir20** [comment]
@zeus3rd ?

**Comment by elias-winberg** [comment]
Maybe it has something to do with file permissions?

**Comment by zeus3rd** [comment]
No,

As I stated previously, we build a distribution folder on a CI server and then deploy that folder to a production server. The distribution folder's path on the CI server differs from the distribution folder's path on the Production server, which is natural.

Prior to one of these updates that folder path difference didn't matter, phantom was included and used regardless and I guess it was because the path was relative tot he project's folder or the node_modules folder. But now when the folder moves from one server to another the change in path affects phantom.

As I said, we've fixed this and we don't need help, but you should inform your users or make changes that implement the old process so no one has this problem.

**Comment by amir20** [comment]
Sounds like you have a bug in your system @zeus3rd. The paths are still the same and none of that has changed. I investigated a little and there is nothing that has been committed to break this. No one else has opened any requests similar to this. So I am guessing it's unique to your environment. 

Best of luck.

**Comment by NaitoKenzo** [comment]
I've got the same error in a docker container:
docker container from https://github.com/nodejs/docker-node/blob/6a984d5b1f27b0344cbbab20019e77e6c0420b91/6.3/Dockerfile
node 6.3.0
phantom 2.1.20

Looks like the binary was installed here: /usr/local/lib/node_modules/phantom/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

```
error: Could not spawn [/usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs] executable. Please make sure phantomjs is installed correctly.
error:  Error: spawn /usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs ENOENT
at exports._errnoException (util.js:1008:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
at onErrorNT (internal/child_process.js:348:16)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by amir20** [comment]
Here is the dockerfile that worked in the past

```
FROM ubuntu:15.10
MAINTAINER Amir Raminfar <findamir@gmail.com>

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_5.x | bash -
RUN apt-get install -y nodejs build-essential g++ flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev python libx11-dev libxext-dev

RUN npm install phantom co

COPY simple.js simple.js
```

**Comment by amir20** [comment]
You should install all dependencies.

**Comment by tonybranfort** [comment]
@amir20 - First thanks very much for your work on this.  

I have 2 identical code deployments on the same aws linux instance (ami-hvm-2016.09.1.20170119-x86_64-gp2 ).  Both code deployments include phantomjs-node v2.1.21 in their npm packages ("phantom": "2.1.21").  phantomjs is installed -g.  Both are deployed and installed in exactly the same manner. One of the code deployments works just fine.  The other cannot find phantomjs : "Error: PhantomJS binary was not found. This generally means something went wrong when installing phantomjs-prebuilt" pointing at "...node_modules/phantom/lib/index.js:20:20" in the error stack.  

I have re-deployed each of the code deployments and uninstalled / reinstalled phantomjs.  Same result - one works and the other doesn't consistently.  Any ideas?  

I included it on this issue as it seemed it might be similar (??).  If not, I'm happy to create a new issue.  

Thanks again.

**Comment by amir20** [comment]
@tonybranfort I really can't think of what could make something like this break. Especially on the same instance. A couple of thoughts, have you tried installing phantom via apt or yum instead? Other idea, try using node cli and require phantomjs. Can you see what the location of the path is? 

On a different note, I highly recommend docker. I know it is completely different solution but if you are deploying a lot and have a few dependencies that must be installed, then containers are better. Just a thought. 

Let me know if my other ideas help.

**Comment by tonybranfort** [comment]
Re-installing phantomjs with just a straight download rather than using the npm phantom resolved it.  That was a leftover from my initial setup a couple years ago when I was still trying to figure out the difference between phantomjs, the npm package phantom and your phantomjs-node.  100% agree on going to docker.  It's on the path to get there.  Thanks again.  Your response and time on this is much appreciated. 

Just for anyone else running across this.  This is the what I used (basis at least) to ditch the npm phantom package and just install phantomjs directly (with a quick search, I didn't see a yum package):
https://www.codeammo.com/article/install-phantomjs-amazon-linux
http://phantomjs.org/download.html
